# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_auto_20161015_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='lpost_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
    ]
