# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_posted',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_pic/'),
        ),
    ]
