# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_remove_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email_id',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_posted',
            field=models.ImageField(upload_to='uploaded_pic/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.User'),
        ),
    ]
