# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0013_post_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email_id',
        ),
    ]
