# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0014_remove_post_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
