# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0017_auto_20161104_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
