# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0018_auto_20161105_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no_of_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
